<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>Sienar</RootNamespace>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<PackageId>Sienar.Ui</PackageId>
		<Title>Sienar.Ui</Title>
		<PackageVersion>0.1.1</PackageVersion>
		<PackageReleaseNotes>Initial release</PackageReleaseNotes>
		<Authors>Christian LeVesque</Authors>
		<Description>Contains a library of tag helpers to make authoring Razor Pages apps more productive</Description>
		<Copyright>Copyright 2024 Christian LeVesque</Copyright>
		<PackageProjectUrl>https://sienar.io</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/christianlevesque/sienar</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>sienar framework utilities razor plugin</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"/>
	</ItemGroup>

</Project>
