<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RootNamespace>TestProject</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RazorForms.Bootstrap5" Version="2.0.0"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Sienar.Ui\Sienar.Ui.csproj" />
		<ProjectReference Include="..\..\src\Sienar.Plugins.Identity\Sienar.Plugins.Identity.csproj" />
		<ProjectReference Include="..\..\src\Sienar.Plugins.MailKit\Sienar.Plugins.MailKit.csproj" />
		<ProjectReference Include="..\TestProject.Data\TestProject.Data.csproj" />
	</ItemGroup>

</Project>
